### ISSUE TITLE
Snapshot

### ISSUE THREAD

**Issue by bradlysnyder2021** [cornertime/cornertime#23]
Would be great if when movement is detected a picture/video snapshot is taken and either downloaded to the local machine or available to view with the report. This would allow better understanding of the information in the report about what happened and wether the miscreant actually moved etc. Versus just a count of how many times movement was detected or sound heard etc.

**Comment by japsu** [comment]
Thank you for your suggestion. While I see how this feature could be used, it would require a re-design of the whole report functionality. Photos are too large to be included in a copy-pasteable report, so it would have to be a file that is downloaded. In order to keep the application simple and code base compact, I will not be implementing this feature.
